### ISSUE TITLE
Use relative paths for UI

### ISSUE THREAD

**Issue by ToeiRei** [shlinkio/shlink-web-client-angularjs#35]
Installation in a subdir not possible without mangling the files.

**Comment by acelaya** [comment]
I prefer to use absolute paths because they are less error prone.
Usually you can use a subdomain instead of a sub path.
However, I'll try to change that.
In the meantime, you can use https://app.shlink.io with your own servers, or fix it yourself and open a pull request :-)

**Comment by acelaya** [comment]
I have tried to deal with this, and my intention was to include it in next release. However, relative paths are problematic when working with the HTML5 history API.
I would suggest you my original approach, working with a subdomain, and I'll try to investigate this in the future.

**Comment by ToeiRei** [comment]
what about making those paths a config option? if it's your subdomain solution, 'path' would be /

**Comment by acelaya** [comment]
Yes, but where do you configure that?
That would force every path in the app to be dynamic, but at least the first script that is loaded, the one that manages that config, needs to have a hardcoded path, which won't work.

I don't see an easy solution here, but I'll investigate how other projects deal with this.

If you know the solution, a pull request is more than welcome :)

**Comment by acelaya** [comment]
I'm closing this for the lack of activity
