### ISSUE TITLE
Add server... but keep in loop.

### ISSUE THREAD

**Issue by erikperin** [shlinkio/shlink-web-client-angularjs#51]
I tried to add a server, but... when I create a shorturl keeping in load... and loop.
That need to open a specific port?

**Comment by acelaya** [comment]
Nop. Just the base URL and a valid API key.

However, if you are using the client instance from https://app.shlink.io, depending on the browser (chrome, for example), requests could be blocked if you are not using https in your shlink server.

You will have to manually disable the blocking. Look for some kind of warning sign in the URL bar of your browser.

**Comment by acelaya** [comment]
You can also host the shlink client yourself if you prefer so.

**Comment by erikperin** [comment]
HTTPS on

But the problem repeat

**Comment by acelaya** [comment]
Hmm.

Could you give me access to your shlink instance? I just need the URL and an API key that you can revoke later. I promise I won't make a mess, I just need it to see the actual error :)

Send it to [alejandro *at* alejandrocelaya *dot* com]

**Comment by erikperin** [comment]
I sent you a mail with info

**Comment by acelaya** [comment]
Fixed via https://github.com/shlinkio/shlink/issues/135
