### ISSUE TITLE
Provided URL is invalid. Try with a different one.

### ISSUE THREAD

**Issue by jingjing123123** [shlinkio/shlink-web-client-angularjs#53]
When I try to add a jump link, show invalid link.
Do not know if there is a solution.

**Comment by acelaya** [comment]
What do you mean by "jump link"?

**Comment by jingjing123123** [comment]
Sorry,my bad. 
I added a link but showed “URL is invalid”.The link is office365's sharepoint.
I don't know why this problem occurs.
Do you know why?
Thanks.

**Comment by acelaya** [comment]
This is probably not a shlink-web-client error, but a shlink error itself.

By default, shlink validates that all provided URLs return a status 200, returning that message if they don't.

Is your office URL public? Does it require authentication? If it is not public, you will recive that error.

However, that behavior can be configured. Open the file `config/params/generated_config.php`, and at the bottom, you should see something like this:

```php
'url_shortener' => array(
    'domain' => array(
        // ...
    ),
    'shortcode_chars' => '...',
    'validate_url' => true, // <- You need to set this to false
),
```

Change the `validate_url` param to `false`. If it is not there, add it.

Then, delete the file `data/cache/app_config.php`. After that change, you should be able to shorten any URL.

**Comment by jingjing123123** [comment]
Wow！As you said, the problem has been solved！
Many many thanks!🙏

**Comment by acelaya** [comment]
Glad to hear that :)
